Support overriding typescript version
TypeStrong/fork-ts-checker-webpack-plugin pull request #100
Opened 2018-02-23 20:55 UTC by Pajn

fixes #99

2018-02-24 10:15 UTC, piotr-oles requested changes

2018-02-24 10:15 UTC, piotr-oles commented on src/CancellationToken.ts
> +  constructor(ts: typeof tsTypes, cancellationFileName: string, isCancelled: boolean) {
I would suggest to stay with `ts` as types namespace and change name from `ts` to `compiler` for a compiler instance.

2018-02-24 11:00 UTC, Pajn commented on src/CancellationToken.ts
> +  constructor(ts: typeof tsTypes, cancellationFileName: string, isCancelled: boolean) {
I followed the pattern in NormalizedMessage, but I have no problem changing if that's preferred.
Should I change NormalizedMessage at the same time to keep things consistent?

2018-02-24 11:02 UTC, piotr-oles commented on src/CancellationToken.ts
> +  constructor(ts: typeof tsTypes, cancellationFileName: string, isCancelled: boolean) {
Yes, please :)

2018-02-24 12:09 UTC, Pajn commented on src/CancellationToken.ts
> +  constructor(ts: typeof tsTypes, cancellationFileName: string, isCancelled: boolean) {
Done

2018-03-05 22:10 UTC, piotr-oles approved these changes

2019-01-19 05:38 UTC, johnnyreilly commented
Closing due to inactivity - if this is still required please could you resubmit.

2019-01-19 05:38 UTC, closed without merging

2020-07-10 22:28 UTC, halfnibble commented
We used to specify the version of the typescript compiler with the `typescript` option. What version did this option get removed in?

2020-07-11 04:14 UTC, johnnyreilly commented
5.0 I believe