Use minimum peer dependencies
TypeStrong/fork-ts-checker-webpack-plugin pull request #134
Opened 2018-08-01 04:10 UTC by nickmccurdy

Fixes #3.

I have used TypeScript 3 with this loader in a CRA-TS app and ran the build and test steps test no issues so far. Let me know if there's anything else we need to change or test.

2018-08-01 04:10 UTC, nickmccurdy commented
@johnnyreilly

2018-08-01 05:07 UTC, johnnyreilly commented
Looks good to me. What do you think @piotr-oles?

2018-08-03 09:03 UTC, piotr-oles requested changes
Please add also cases in .travis.yml for TypeScript 2.x and TypeScript 3.x (using ENV variable - like it's done for ts-loader, ts-lint and vue-loader)

2018-08-03 09:03 UTC, piotr-oles commented on package.json
> +    "tslint": ">= 4.0.0",
It's a bold assumption that next major releases of tslint, typescript and webpack will be compatible with this plugin :) Please add typescript ^3.0.0 instead

2018-08-03 10:21 UTC, nickserv commented on package.json
> +    "tslint": ">= 4.0.0",
I agree. Done.

2018-08-03 10:26 UTC, nickmccurdy commented
I'm not sure if using ENV variables like that for TypeScript would be safe in the future. I updated TypeScript in the package's own devDependencies so you can take advantage of new syntax features, along with the improved project support and error messages. If you change source code to have syntax or config options that are only supported in TS 3, the TS 2 env will fail.

Are you sure you still want to try that? That would mean this package cannot use TS 3 features in its own TS files without changing the build setup further to separate TS transpilation from integration testing other versions of TS in other packages.

2018-08-03 12:52 UTC, piotr-oles commented
Good point - let's keep test as they are currently :) Thank you for your work!

2018-08-03 12:52 UTC, piotr-oles approved these changes

2018-08-03 13:09 UTC, merged