[Feature][#67] Adds tslint autofix as a flag to ForkTsCheckerWebpackPlugin plugin
TypeStrong/fork-ts-checker-webpack-plugin pull request #174
Opened 2018-10-23 21:58 UTC by ajainarayanan

- Adds `tslintAutoFix` as a flag to `ForkTsCheckerWebpackPlugin` plugin in webpack config.
- Set the default to false for backward compatibility.
- Updates Vue integration test based on changes to `IncrementalChecker` class update.

Addresses #67

2018-10-23 21:59 UTC, ajainarayanan commented
@johnnyreilly Changes for adding auto fix as a flag. Let me know if I had missed anything.

2018-10-24 05:32 UTC, johnnyreilly commented
Thanks for this! @piotr-oles what's your feeling on merging this? It's not a feature that I would use but clearly there's some demand out there for this. 

I know you expressed reservations so I don't want to merge unless I know you're okay with this!

2018-10-24 07:29 UTC, piotr-oles commented
Thank you @ajainarayanan for your work! I was afraid that it will add complexity to the plugin but looks like it doesn't. Please add an integration test for tslintAutoFix: true case and update README.md :)

2018-10-25 02:36 UTC, ajainarayanan commented
@piotr-oles @johnnyreilly This is was a tricky change. Have taken an approach that shouldn't affect the other tests. 

There is still one problem with `should fix linting errors with tslintAutofix flag set to true` test. It lints other files as well even though I am explicitly passing in the entry point. Don't know what I am missing but right now my brain is fried and can't think of a reason. Will update the pull request when I have sometime. If you happen to identify the reason as to why it updates other files please do point out and I will fix it.

2018-10-25 03:47 UTC, ajainarayanan commented on package.json
>        ],
Sorry this is not needed. Will remove.

2018-10-25 03:47 UTC, ajainarayanan commented on test/integration/index.spec.js
> +var fs = require('fs');
This as well. Will remove

2018-10-25 05:17 UTC, johnnyreilly commented
@ajainarayanan could you merge in the upstream changes please?

2018-10-25 13:47 UTC, ajainarayanan commented
@johnnyreilly Have updated.

2018-10-25 14:40 UTC, piotr-oles requested changes

2018-10-25 14:40 UTC, piotr-oles commented on test/integration/index.spec.js
> +          expect(stats.compilation.warnings.length).to.be.eq(0);
could you also check if content of the file is proper after fixing?

2018-10-26 02:08 UTC, ajainarayanan commented
@piotr-oles @johnnyreilly Have updated the pull request. Can you give it another review.

2018-10-28 09:27 UTC, johnnyreilly commented
Just merged in upstream changes @ajainarayanan.

@piotr-oles are you happy with the amends?

2018-11-01 01:55 UTC, ajainarayanan commented
@johnnyreilly @piotr-oles I know its a little ridiculous to request some changes in an open source library and expect a release to happen right away but I am blocked by this change (or a new version of fork-ts-checker) to integrate prettier into my project.

Do we know tentatively when the pull request will be merged and a release will be cut? If any further changes are required please do let me know and I will make it.

2018-11-01 06:29 UTC, johnnyreilly commented
Hey @ajainarayanan , sorry this is a bit of a frustration for you. From my perspective I'm fine for this to be merged and shipped now. Given @piotr-oles requested changes (which you've generously done!) I'd like him to confirm he's happy with the work rather than me merge directly.

If there's no response from him by the weekend then ping me again, maybe we can proceed without him. But that's not my preference.

Apologies for the delay; I understand the frustration.

2018-11-06 23:01 UTC, johnnyreilly commented
Okay let's do this! Do you want to update the `package.json` and the `CHANGELOG.md`? Then I can cut a release.

2018-11-07 02:26 UTC, ajainarayanan commented
@johnnyreilly Thanks! Have updated both. Could you give it a review?

2018-11-07 06:01 UTC, johnnyreilly commented
Looks good - could you put the Default value of the field in the `README.md` please? Then we're good to go!

2018-11-07 13:44 UTC, piotr-oles approved these changes

2018-11-07 13:46 UTC, piotr-oles commented
Thank you for your work and sorry for blocking this PR. Like @johnnyreilly said, please add default value to the README.md and then we're ready for release :)

2018-11-07 20:11 UTC, ajainarayanan commented
@piotr-oles @johnnyreilly Updated. Thanks for the review.

2018-11-07 20:26 UTC, merged

2018-11-07 20:28 UTC, johnnyreilly commented
Thanks! Should be available shortly