prepare next release
TypeStrong/fork-ts-checker-webpack-plugin pull request #275
Opened 2019-04-30 15:37 UTC by phryneas

2019-04-30 15:40 UTC, phryneas commented
So we'd need to make a new release for the changes from #274 to land in the README. Also this lands a few test improvements and `feat(apiincrementalchecker): improve generation of diagnostics`.

Since the `beta` branch is protected I don't really know how to best prepare merging this into master @piotr-oles, can you help here?

2019-04-30 16:25 UTC, piotr-oles commented
I will take a look today’s evening :)

2019-04-30 19:49 UTC, piotr-oles commented
I've resolved conflicts in the `CHANGELOG.md` - now everything should be good. I think semantic-release will release new beta version (1.2.1-beta.1).

2019-04-30 19:59 UTC, piotr-oles submitted a review, later dismissed

2019-04-30 20:27 UTC, phryneas commented
Great! Who wants to pull the trigger? :smile:

2019-05-01 05:02 UTC, johnnyreilly submitted a review, later dismissed
First time with the semantic release hotness!

2019-05-01 05:05 UTC, johnnyreilly commented
It looks like we can't merge as Travis isn't running or something... @piotr-oles can you investigate please?

2019-05-01 07:21 UTC, piotr-oles submitted a review, later dismissed

2019-05-01 07:24 UTC, piotr-oles commented
We have all these problems because not all commits were merged into beta :) Travis didn't want to build because when we merged master to beta, semantic-release created new release and updated CHANGELOG.md with `[skip ci]` in the commit message. That why travis didn't want to start build. I have created a new commit with some spacing changes in the CHANGELOG.md to trigger build again without `[skip ci]` in the last commit :)

2019-05-01 07:31 UTC, johnnyreilly commented
Cool - is there a way we can avoid this happening in future? I'm keen we have a release process that just works™️ 😊

Is this happening just because this will be our first release end to end with semantic release? So in future these issues won't present? 

I'm a little confused / concerned with the problems we've been facing getting semantic release bedded in. Hopefully we can get past this and into a good release flow 🤞

2019-05-01 07:47 UTC, swashata requested changes
I have found a typo in the docs. Please accept the changes in this PR too :)

2019-05-01 07:47 UTC, swashata commented on README.md
> +// These hooks provide acess to different events
Oops for the typo

```suggestion
// These hooks provide access to different events
```

2019-05-01 08:14 UTC, piotr-oles commented
The most problematic is generation of the `CHANGELOG.md` - I think that's why it's not in the default semantic-release setup. After we merge to the `master` it creates additional commit with updated `CHANGELOG.md`. This commit doesn't appear in the `beta` branch and this creates merge conflicts in the next pull request (as we modify `CHANGELOG.md` in every beta release). We can manualy merge the master barnch into the beta after release but maybe we could automate this also (that was the point of the semantic-release)

2019-05-01 08:24 UTC, johnnyreilly commented
My take away from that is that semantic release doesn't have a good workflow with regards to changelogs. That's super disappointing. 

I'm rather hesitant about us creating our own automation around this as that may end up being another thing to maintain as semantic release evolves. If there's not a good out of the box experience that we can have I'm inclined to say "well nevermind - let's just have the GitHub releases instead"

It means we have to be online to see them and if we were ever to move the plugin elsewhere we'd need to recreate manually. Neither of those is a deal-breaker in my eyes.

I value a simple release workflow above other concerns. If you want to drop the changelog generation I'm fine with that. 😊

2019-05-01 08:25 UTC, piotr-oles submitted a review, later dismissed

2019-05-01 08:32 UTC, phryneas commented
Since the CHANGELOG is automatically generated from commit messages, I think we won't lose any metadata when dropping the automatic generation - even if this project were to move away from github some day in the future. The commit history won't be lost.

2019-05-01 09:25 UTC, piotr-oles commented
I've created PR to drop `CHANGELOG.md` generation and remove emoji as not everyone is using them 😢

2019-05-01 10:11 UTC, piotr-oles commented
The last thing we should remember is to use "Rebase and merge" when merging from the `beta` to `master` - that will not create additional commit and will create a tag with the new version on the last commit that was also on the beta branch. Thanks to that master and beta will be in sync (otherwise master will be 1 commit ahead of beta - the merge commit). I will create PR with docs update for the deployment process.

2019-05-01 10:33 UTC, johnnyreilly commented
Good catch - thanks!

2019-05-02 07:41 UTC, piotr-oles approved these changes

2019-05-02 11:23 UTC, merged

2019-05-02 11:54 UTC, piotr-oles commented
:tada: This PR is included in version 1.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/fork-ts-checker-webpack-plugin)
- [GitHub release](https://github.com/Realytics/fork-ts-checker-webpack-plugin/releases/tag/v1.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2019-05-02 17:22 UTC, johnnyreilly commented
How did you get it to work? Can you just not rebase on a phone?

2019-05-02 17:30 UTC, phryneas commented
Nope, looks like this was one last normal merge. I guess we'll have to rebase that one back to beta one last time and then we'll be golden as long as we don't push to master.