feat: support eslint fix (#323)
TypeStrong/fork-ts-checker-webpack-plugin pull request #342
Opened 2019-10-11 07:05 UTC by viljark

2019-10-15 14:59 UTC, o-alexandrov commented
Would be greatly appreciated when released, thank you :)

2019-10-15 18:41 UTC, johnnyreilly commented
I'd like to get this out there but we need the points I raised to be addressed

2019-10-15 18:49 UTC, phryneas commented
@johnnyreilly  At least in this PR, there are no comments visible - did you start a review and never click finish? Happened to me once.

2019-10-22 20:43 UTC, johnnyreilly requested changes

2019-10-22 20:43 UTC, johnnyreilly commented on src/createEslinter.ts
> +export function createEslinter(eslintOptions: eslinttypes.CLIEngine.Options) {
Whilst I'd love to take the ESLint options type here I don't believe we can as we then make ESLint a dependency of the plugin. Not everyone uses ESLint and hence that's why we haven't done that. The `object` is necessary to prevent that I believe. Could you revert this back please?

2019-10-22 20:44 UTC, johnnyreilly commented
You may be right...

2019-10-23 09:22 UTC, o-alexandrov commented
@johnnyreilly why not making that as an `optionalDependency` and doing [conditional require](https://stackoverflow.com/a/40277993), not a top-level import?
- while ES6 [dynamic imports](https://github.com/tc39/proposal-dynamic-import) will be available soon, it's still a proposal that's as of now in [stage 4](https://tc39.es/process-document/) 

That way:
- those, who are not using ESLint would not need to install additional deps
- those, who are using ESLint, would just

2019-10-23 11:37 UTC, johnnyreilly commented
> while ES6 dynamic imports will be available soon, it's still a proposal that's as of now in stage 4

I'm not sure I follow what this refers to?

>  not making that as an optionalDependency or peerDependency

That's worth considering; what would the implications of each choice be?

2019-10-23 11:49 UTC, o-alexandrov commented
@johnnyreilly to achieve what you mentioned above:
> I don't believe we can as we then make ESLint a dependency of the plugin

You can conditionally require ESLint. That way, who doesn't use ESLint, won't need it as a dependency.
Whereas those, who are using ESLint, if you say the plugin then needs ESLint as a dependency, then those users would need to install ESLint as `peerDependencies` or `optionalDependencies` suggest.

> while ES6 dynamic imports will be available soon, it's still a proposal that's as of now in stage 4
> > I'm not sure I follow what this refers to?
In the future, we might be able to use dynamic imports instead of conditional require statement.
- please ignore it, as of now this particular option would add additional complexity

2019-10-23 12:01 UTC, o-alexandrov commented
@viljark 
cc @johnnyreilly 
Based on the code changes, the `eslint` module is imported for `typescript` only.

So it would be removed from the runtime, if not used as a value (not for `typescript`), therefore, conditional require in this particular case shouldn't be needed, unless you have other plans (use `eslint` as a value, not a type).

Please correct me, if I'm wrong @viljark

2019-10-23 17:27 UTC, phryneas commented
The problem is that from that point on, our types would contain a reference to eslint, which would require people using our types to also install eslint. (And since we're distributing the types with the package, they essentially become dependencies.)
We've had a similar problem with webpack's types, which in the end lead to `@types/node` being installed as a requirement and subsequently polluting the global scope. That's why we're trying to keep our types as independent from other libraries as possible.

Also, as far as I can tell, types cannot be `import`ed dynamically. Either they're in, or not.

2019-10-23 18:33 UTC, o-alexandrov commented
@phryneas based on my experience, if you don't have a `@types/eslint` dependency installed, the typescript compiler would process it as `any` type.
Have you actually tried it without the dependency `@types/eslint` installed?

I will also check it later today.

2019-10-23 20:39 UTC, o-alexandrov commented on src/createEslinter.ts
>    const eslint: typeof eslinttypes = require('eslint');
@johnnyreilly you conditionally require `eslint` here, your argument that you then need to make `ESLint` a dependency isn't valid as it is not a top-level import and eslint above is used as the type.

2019-10-23 20:41 UTC, o-alexandrov commented
@phryneas just checked the type of `eslinttypes`, if no `@types/eslint` is installed, it works as I mentioned before, it has the `any` type.

Hopefully the following clears the concern, you could refer to the screenshot below:
<img width="967" alt="Screen Shot 2019-10-23 at 3 33 51 PM" src="https://user-images.githubusercontent.com/9992724/67431977-fc70b100-f5aa-11e9-826c-def9615ea93c.png">

But, [you already have](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/blob/master/package.json#L111) the `@types/eslint` `devDependency` and @viljark doesn't mess with the deps according to the code changes in the PR.

Sorry for pinging too much, I'm just interested to see this PR being released 😆

2019-10-23 21:46 UTC, johnnyreilly commented
`devDependency`s are fine, as are internal type usage which is what `createEslinter` is. For the reasons stated, I don't think we're going to be able to make `@types/eslint` a prod dependency of the plugin. We did similar previously and had to back it out because of the issues it caused.

Are you interested in proceeding with the feature without making `@types/eslint` a prod dependency?

2019-10-24 05:53 UTC, phryneas commented
So I just created a new project, installed typescript and 'fork-ts-checker-webpack-plugin', set `skipLibCheck: false` and edited `import X from 'eslint';`into the `index.d.ts` (also I used it further down in one of the types).

Result when running `tsc`:

```

node_modules/fork-ts-checker-webpack-plugin/lib/index.d.ts:5:15 - error TS2307: Cannot find module 'eslint'.

5 import X from 'eslint';
      
```

(And yes, we have two more of those errors already in there for webpack and tapable, that's over in https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/339 - I hopefully get around to removing those references this weekend.

2020-02-24 03:48 UTC, linxiaowu66 commented
this feature has any update? @johnnyreilly

2020-03-12 08:23 UTC, piotr-oles commented
Resolved in #395

2020-03-12 08:23 UTC, closed without merging